# File generated by CompCert 3.13
# Command line: -c -S encrypt.c encrypt.s
	.section      .rodata
	.align	4
	.globl	key
key:
	.long	42
	.type	key, @object
	.size	key, . - key
	.text
	.align	16
	.globl encrypt
encrypt:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	key(%rip), %eax
	xorl	%eax, %edi
	movl	%edi, 0(%rsi)
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	encrypt, @function
	.size	encrypt, . - encrypt
